name: Release
on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Install deps
        run: pnpm install

      - name: Code Check
        run: pnpm run lint

      - name: Release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
